// MotionMatrix 핵심 옵션 — Target Model / Animation Mode / Layered FX / Dynamics.
// 기존 motion 카테고리(generic loop/intro/FX)는 그대로 유지. 이 파일은 별도 카테고리(motion-matrix)로 분리.

export const motionMatrixCards = [
  {
    id: 'mm_target', title: 'Target AI 모델', importance: 'critical',
    summary: 'Veo / Runway / Kling / Gemini / Luma',
    fields: [
      { key: 'model', label: '타겟 모델', type: 'choice',
        choices: ['universal', 'runway', 'kling', 'gemini', 'luma'], default: 'universal',
        map: { universal: 'universal video model (Veo, Pika)',
               runway: 'Runway Gen — anti-zoom directives applied',
               kling: 'Kling 3.0 — internal texture dynamics, frozen outline',
               gemini: 'Gemini video — minimalist clean motion',
               luma: 'Luma Dream Machine — fluid cinematic motion' } },
    ],
    promptFn: (v, f) => `Target model: ${f[0].map[v.model]}.`,
  },
  {
    id: 'mm_mode', title: 'Animation Mode', importance: 'critical',
    summary: 'Loop · Intro',
    fields: [
      { key: 'mode', label: '모드', type: 'choice',
        choices: ['loop', 'intro'], default: 'loop',
        map: { loop: 'infinite seamless loop animation, frame N matches frame 0',
               intro: 'intro reveal — frame 0 is pitch black, subject fully visible at end' } },
    ],
    promptFn: (v, f) => `Animation mode: ${f[0].map[v.mode]}.`,
  },
  {
    id: 'mm_surface_fx', title: 'Surface FX', importance: 'editable',
    summary: '피사체 표면 효과',
    fields: [
      { key: 'fx', label: 'Surface FX', type: 'choice',
        choices: ['none', 'metallicSweep', 'chromeShimmer', 'liquidGold', 'pulsingGlow', 'frostFormation'], default: 'metallicSweep',
        map: { none: 'no surface FX',
               metallicSweep: 'metallic highlight sweep across the front face',
               chromeShimmer: 'chrome shimmer with specular peaks',
               liquidGold: 'liquid gold material flowing slowly',
               pulsingGlow: 'pulsing internal glow breathing in sync',
               frostFormation: 'frost crystals forming and dissolving on surface' } },
    ],
    promptFn: (v, f) => `Surface FX: ${f[0].map[v.fx]}.`,
  },
  {
    id: 'mm_edge_fx', title: 'Edge FX', importance: 'editable',
    summary: '외곽 라인 효과',
    fields: [
      { key: 'fx', label: 'Edge FX', type: 'choice',
        choices: ['none', 'rimTrace', 'goldOutline', 'electricArc', 'fireRim', 'crystalEdge'], default: 'rimTrace',
        map: { none: 'no edge FX',
               rimTrace: 'rim light tracing the outline',
               goldOutline: 'warm gold outline glow',
               electricArc: 'electric arcs along the edges',
               fireRim: 'fire embers along the rim',
               crystalEdge: 'crystalline frost on the edge' } },
    ],
    promptFn: (v, f) => `Edge FX: ${f[0].map[v.fx]}.`,
  },
  {
    id: 'mm_ambient_fx', title: 'Ambient FX', importance: 'optional',
    summary: '주변 공간 효과',
    fields: [
      { key: 'fx', label: 'Ambient FX', type: 'choice',
        choices: ['none', 'goldDust', 'fireSparks', 'frostMotes', 'magicGlyphs', 'energyWaves'], default: 'none',
        map: { none: 'no ambient FX',
               goldDust: 'warm gold dust motes drifting upward',
               fireSparks: 'floating fire sparks and embers',
               frostMotes: 'frost motes suspended in cold air',
               magicGlyphs: 'rotating magic glyphs glowing softly',
               energyWaves: 'concentric energy waves emanating outward' } },
    ],
    promptFn: (v, f) => `Ambient FX: ${f[0].map[v.fx]}.`,
  },
  {
    id: 'mm_dynamics', title: 'Dynamics', importance: 'essential',
    summary: '동작 흐름 · 강도 · 길이',
    fields: [
      { key: 'flow', label: 'Flow', type: 'choice',
        choices: ['contourTrace', 'pulseBreath', 'sweepWave', 'orbitalRotation'], default: 'contourTrace',
        map: { contourTrace: 'contour-tracing light flow',
               pulseBreath: 'pulse breathing rhythm',
               sweepWave: 'sweeping wave across the subject',
               orbitalRotation: 'orbital rotation around the center' } },
      { key: 'dynamics', label: 'Dynamics', type: 'choice',
        choices: ['smooth', 'sharp', 'organic', 'mechanical'], default: 'smooth',
        map: { smooth: 'smooth easeInOut motion',
               sharp: 'sharp snappy motion',
               organic: 'organic natural curves',
               mechanical: 'mechanical precise motion' } },
      { key: 'intensity', label: 'Intensity', type: 'choice',
        choices: ['subtle', 'balanced', 'intense'], default: 'subtle',
        map: { subtle: 'subtle low-key intensity',
               balanced: 'balanced moderate intensity',
               intense: 'intense high-energy intensity' } },
      { key: 'duration', label: 'Duration (s)', type: 'choice',
        choices: ['3s', '5s', '8s', '10s'], default: '5s',
        map: { '3s': '3 seconds total', '5s': '5 seconds total',
               '8s': '8 seconds total', '10s': '10 seconds total' } },
    ],
    promptFn: (v, f) =>
      `Dynamics: ${f[0].map[v.flow]}, ${f[1].map[v.dynamics]}, ${f[2].map[v.intensity]}, ${f[3].map[v.duration]}.`,
  },
];
