import { useState, useMemo } from 'react';
import { 
  Award, 
  FileText, 
  TrendingUp, 
  TrendingDown,
  RefreshCcw 
} from 'lucide-react';

const safeRender = (value) => value || '';

const AnalysisDashboard = ({ banners, onOpenPreview }) => {
    const [selectedYear, setSelectedYear] = useState(new Date().getFullYear());
    const [selectedQuarter, setSelectedQuarter] = useState(Math.ceil((new Date().getMonth() + 1) / 3));

    const stats = useMemo(() => {
        const yearStats = {};
        const monthStats = {}; 
        const quarterStats = {}; 

        banners.forEach(b => {
            const dateStr = b.created_at || b.createdAt; 
            const date = dateStr ? new Date(dateStr) : new Date();
            const year = date.getFullYear();
            const month = date.getMonth() + 1;
            const quarter = Math.ceil(month / 3);
            
            let score = b.designScore || 0;
            if (score > 10) score = score / 10;
            score = Math.min(score, 9.8);
            
            const hasScore = score > 0;

            if (!yearStats[year]) yearStats[year] = { count: 0, totalScore: 0, scoredCount: 0 };
            yearStats[year].count += 1;
            if (hasScore) {
                yearStats[year].totalScore += score;
                yearStats[year].scoredCount += 1;
            }

            const mKey = `${year}-${String(month).padStart(2, '0')}`;
            if (!monthStats[mKey]) monthStats[mKey] = { count: 0, totalScore: 0, scoredCount: 0 };
            monthStats[mKey].count += 1;
            if (hasScore) {
                monthStats[mKey].totalScore += score;
                monthStats[mKey].scoredCount += 1;
            }

            const qKey = `${year}-Q${quarter}`;
            if (!quarterStats[qKey]) quarterStats[qKey] = { count: 0, totalScore: 0, scoredCount: 0, items: [] };
            quarterStats[qKey].count += 1;
            quarterStats[qKey].items.push({ ...b, designScore: score });
            if (hasScore) {
                quarterStats[qKey].totalScore += score;
                quarterStats[qKey].scoredCount += 1;
            }
        });

        return { year: yearStats, month: monthStats, quarter: quarterStats };
    }, [banners]);

    const currentQuarterData = useMemo(() => {
        const key = `${selectedYear}-Q${selectedQuarter}`;
        const data = stats.quarter[key];
        if (!data) return { best: [], worst: [], count: 0, avgScore: 0 };

        const scoredItems = data.items.filter(i => i.designScore > 0).sort((a, b) => b.designScore - a.designScore);
        
        return {
            best: scoredItems.slice(0, 3),
            worst: scoredItems.slice(-3).reverse(), 
            count: data.count,
            avgScore: data.scoredCount > 0 ? (data.totalScore / data.scoredCount).toFixed(1) : 0
        };
    }, [stats, selectedYear, selectedQuarter]);

    const availableYears = Object.keys(stats.year).sort().reverse();
    if (availableYears.length === 0) availableYears.push(new Date().getFullYear());

    const handleDownloadReport = () => {
        const { best, worst, count, avgScore } = currentQuarterData;
        
        let report = `# ${selectedYear}년 ${selectedQuarter}분기 프로모션 디자인 성과 리포트\n`;
        report += `작성일: ${new Date().toLocaleDateString()}\n\n`;
        
        report += `## 1. 개요 (Overview)\n`;
        report += `- **발행 기간:** ${selectedYear}년 ${selectedQuarter}분기\n`;
        report += `- **총 제작 건수:** ${count}건\n`;
        report += `- **평균 디자인 점수:** ${avgScore}점 / 10.0\n\n`;
        
        report += `## 2. Best Performance (Top 3)\n`;
        if (best.length > 0) {
            best.forEach((item, index) => {
                report += `### ${index + 1}. ${item.title || 'Untitled'} (${item.designScore}점)\n`;
                report += `- **게임:** ${item.game}\n`;
                report += `- **AI 총평:** ${item.verdict || item.summary || 'N/A'}\n`;
                report += `- **주요 특징:** ${item.tags ? item.tags.join(', ') : 'N/A'}\n\n`;
            });
        } else {
            report += `데이터가 없습니다.\n\n`;
        }

        report += `## 3. Needs Improvement (Bottom 3)\n`;
        if (worst.length > 0) {
            worst.forEach((item, index) => {
                report += `### ${index + 1}. ${item.title || 'Untitled'} (${item.designScore}점)\n`;
                report += `- **게임:** ${item.game}\n`;
                report += `- **개선 포인트:** ${item.improvement || item.designEvaluation?.critical_issue || 'N/A'}\n\n`;
            });
        } else {
            report += `데이터가 없습니다.\n\n`;
        }
        
        report += `\n---\n*Generated by Promotion Archive AI System*`;

        const blob = new Blob([report], { type: 'text/markdown;charset=utf-8;' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `Design_Report_${selectedYear}_Q${selectedQuarter}.md`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    };

    return (
        <div className="flex flex-col gap-6 pb-32 w-full">
            {/* Header Area */}
            <div className="sticky top-0 z-30 bg-[#0c0c0e]/95 backdrop-blur-sm py-4 mb-2 flex items-center justify-between border-b border-white/5">
                
                {/* Left: Title */}
                <div className="flex items-center gap-2 md:gap-4">
                    <h2 className="text-base md:text-lg font-bold text-white leading-none">
                        프로모션 성과 분석
                    </h2>
                    <span className="text-zinc-500 text-xs font-normal hidden sm:inline border-l border-zinc-700 pl-3 ml-1 leading-none">
                        디자인 평가 점수 현황
                    </span>
                </div>

                {/* Right: Controls */}
                <div className="flex items-center gap-3"> 
                    <span className="text-[10px] text-zinc-500 hidden md:inline">
                        Last updated: {new Date().toLocaleDateString()}
                    </span>
                    
                    <button 
                        onClick={() => window.location.reload()} 
                        className="p-2 rounded-lg text-zinc-400 hover:text-white hover:bg-zinc-800 transition-colors"
                        title="새로고침"
                    >
                        <RefreshCcw className="w-5 h-5" />
                    </button>
                </div>
            </div>

            {/* KPI Cards */}
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                <div className="bg-zinc-900 border border-zinc-800 p-4 rounded-xl">
                    <div className="text-zinc-500 text-xs font-bold mb-1">총 제작 건수</div>
                    <div className="text-2xl font-bold text-white">{banners.length} <span className="text-sm font-normal text-zinc-500">건</span></div>
                </div>
                <div className="bg-zinc-900 border border-zinc-800 p-4 rounded-xl">
                    <div className="text-zinc-500 text-xs font-bold mb-1">평균 디자인 점수</div>
                    <div className="text-2xl font-bold text-[#d8b17e]">
                        {banners.length > 0 ? (
                            (banners.reduce((acc, b) => {
                                let s = b.designScore || 0;
                                if (s > 10) s = s / 10;
                                s = Math.min(s, 9.8);
                                return s > 0 ? acc + s : acc;
                            }, 0) / Math.max(1, banners.filter(b => b.designScore > 0).length)).toFixed(1)
                        ) : '0.0'}
                        <span className="text-sm font-normal text-zinc-500"> / 10</span>
                    </div>
                </div>
                 <div className="bg-zinc-900 border border-zinc-800 p-4 rounded-xl">
                    <div className="text-zinc-500 text-xs font-bold mb-1">올해 제작 ({new Date().getFullYear()})</div>
                    <div className="text-2xl font-bold text-white">{stats.year[new Date().getFullYear()]?.count || 0} <span className="text-sm font-normal text-zinc-500">건</span></div>
                </div>
                <div className="bg-zinc-900 border border-zinc-800 p-4 rounded-xl">
                    <div className="text-zinc-500 text-xs font-bold mb-1">분석 완료율</div>
                    <div className="text-2xl font-bold text-emerald-400">
                        {Math.round((banners.filter(b=>b.designScore).length / Math.max(1, banners.length)) * 100)}%
                    </div>
                </div>
            </div>

            {/* 분기별 리포트 섹션 */}
            <div className="bg-[#151517] border border-zinc-800 rounded-2xl p-6 space-y-6">
                <div className="flex items-center justify-between flex-wrap gap-4 border-b border-zinc-800 pb-4">
                    <div className="flex items-center gap-2">
                        <Award className="w-5 h-5 text-[#d8b17e]" />
                        <h3 className="text-lg font-bold text-white">분기별 리포트</h3>
                    </div>
                    <div className="flex items-center gap-3">
                        <div className="flex gap-2">
                             <select 
                                value={selectedYear} 
                                onChange={(e) => setSelectedYear(Number(e.target.value))}
                                className="bg-zinc-900 border border-zinc-700 text-white text-sm rounded-lg px-3 py-2 outline-none focus:border-[#d8b17e]"
                            >
                                {availableYears.map(y => <option key={y} value={y}>{y}년</option>)}
                            </select>
                            <select 
                                value={selectedQuarter} 
                                onChange={(e) => setSelectedQuarter(Number(e.target.value))}
                                className="bg-zinc-900 border border-zinc-700 text-white text-sm rounded-lg px-3 py-2 outline-none focus:border-[#d8b17e]"
                            >
                                {[1,2,3,4].map(q => <option key={q} value={q}>{q}분기</option>)}
                            </select>
                        </div>
                        <button 
                            onClick={handleDownloadReport}
                            className="flex items-center gap-2 bg-[#d8b17e] hover:bg-[#c6a36e] text-black text-sm font-bold px-3 py-2 rounded-lg transition-colors shadow-lg shadow-[#d8b17e]/10"
                            title="리포트 다운로드 (.md)"
                        >
                            <FileText className="w-4 h-4" /> 
                            <span className="hidden sm:inline">리포트 생산</span>
                        </button>
                    </div>
                </div>

                <div className="flex items-center gap-6 text-sm">
                    <div className="flex items-center gap-2">
                        <span className="text-zinc-500">제작:</span>
                        <span className="text-white font-bold">{currentQuarterData.count}건</span>
                    </div>
                    <div className="flex items-center gap-2">
                        <span className="text-zinc-500">평균 점수:</span>
                        <span className="text-[#d8b17e] font-bold">{currentQuarterData.avgScore}점</span>
                    </div>
                </div>

                {/* Best 3 */}
                <div>
                    <h4 className="text-sm font-bold text-emerald-400 mb-3 flex items-center gap-2">
                        <TrendingUp className="w-4 h-4" /> Best 3 (고득점)
                    </h4>
                    {/* 카드 그리드 */}
                    {currentQuarterData.best.length > 0 ? (
                        <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-5 gap-4">
                            {currentQuarterData.best.map((item, idx) => (
                                <div key={item.id} className="bg-zinc-900 rounded-lg overflow-hidden border border-zinc-800 hover:border-[#d8b17e] transition-colors cursor-pointer group" onClick={() => onOpenPreview(item)}>
                                    {/* ✨ 수정됨: object-top 추가 (상단 기준 크롭) */}
                                    <div className="aspect-[4/5] bg-black relative">
                                        <img 
                                            src={item.preview} 
                                            alt={safeRender(item.title)} 
                                            className="w-full h-full object-cover object-top opacity-80 group-hover:opacity-100 transition-opacity" 
                                        />
                                        <div className="absolute top-2 right-2 bg-black/60 backdrop-blur px-2 py-0.5 rounded text-xs font-bold text-[#d8b17e] border border-[#d8b17e]/30">
                                            {item.designScore}
                                        </div>
                                        <div className="absolute top-2 left-2 bg-emerald-500 text-black px-2 py-0.5 rounded text-[10px] font-bold">
                                            TOP {idx + 1}
                                        </div>
                                    </div>
                                    <div className="p-3">
                                        <div className="text-xs font-bold text-white truncate">{safeRender(item.title)}</div>
                                        <div className="text-[10px] text-zinc-500 truncate">{safeRender(item.game)}</div>
                                    </div>
                                </div>
                            ))}
                        </div>
                    ) : (
                        <div className="text-zinc-600 text-xs py-4 text-center bg-zinc-900/50 rounded-lg">데이터가 없습니다.</div>
                    )}
                </div>

                {/* Worst 3 */}
                <div className="pt-4 border-t border-zinc-800/50">
                    <h4 className="text-sm font-bold text-red-400 mb-3 flex items-center gap-2">
                        <TrendingDown className="w-4 h-4" /> Needs Improvement (저득점)
                    </h4>
                    {currentQuarterData.worst.length > 0 ? (
                        <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-5 gap-4">
                            {currentQuarterData.worst.map((item) => (
                                <div key={item.id} className="bg-zinc-900 rounded-lg overflow-hidden border border-zinc-800 hover:border-red-500/50 transition-colors cursor-pointer group" onClick={() => onOpenPreview(item)}>
                                    {/* ✨ 수정됨: object-top 추가 (상단 기준 크롭) */}
                                    <div className="aspect-[4/5] bg-black relative">
                                        <img 
                                            src={item.preview} 
                                            alt={safeRender(item.title)} 
                                            className="w-full h-full object-cover object-top opacity-80 group-hover:opacity-100 transition-opacity" 
                                        />
                                        <div className="absolute top-2 right-2 bg-black/60 backdrop-blur px-2 py-0.5 rounded text-xs font-bold text-red-400 border border-red-500/30">
                                            {item.designScore}
                                        </div>
                                    </div>
                                    <div className="p-3">
                                        <div className="text-xs font-bold text-white truncate">{safeRender(item.title)}</div>
                                        <div className="text-[10px] text-zinc-500 truncate">{safeRender(item.game)}</div>
                                    </div>
                                </div>
                            ))}
                        </div>
                    ) : (
                        <div className="text-zinc-600 text-xs py-4 text-center bg-zinc-900/50 rounded-lg">데이터가 없습니다.</div>
                    )}
                </div>
            </div>
            
            {/* Visual Charts */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                 {/* Monthly Stats */}
                 <div className="bg-zinc-900 border border-zinc-800 rounded-xl p-5">
                    <h3 className="text-sm font-bold text-white mb-4">월별 제작 추이 ({selectedYear}년)</h3>
                    <div className="flex items-end justify-between h-40 gap-2">
                        {Array.from({length: 12}, (_, i) => i + 1).map(m => {
                            const key = `${selectedYear}-${String(m).padStart(2,'0')}`;
                            const count = stats.month[key]?.count || 0;
                            const maxCount = Math.max(...Object.values(stats.month).filter(d => d && typeof d === 'object').map(d => d.count), 10);
                            const height = Math.max((count / maxCount) * 100, 5); 
                            
                            return (
                                <div key={m} className="flex-1 flex flex-col items-center gap-1 group">
                                    <div className="w-full bg-zinc-800 rounded-t relative group-hover:bg-[#d8b17e] transition-colors" style={{ height: `${height}%` }}>
                                        <div className="absolute bottom-full left-1/2 -translate-x-1/2 mb-1 text-[10px] text-white opacity-0 group-hover:opacity-100 transition-opacity">
                                            {count}
                                        </div>
                                    </div>
                                    <div className="text-[10px] text-zinc-500">{m}월</div>
                                </div>
                            )
                        })}
                    </div>
                 </div>

                 {/* Quarterly Stats */}
                 <div className="bg-zinc-900 border border-zinc-800 rounded-xl p-5">
                    <h3 className="text-sm font-bold text-white mb-4">분기별 평균 점수 ({selectedYear}년)</h3>
                    <div className="flex items-end justify-between h-40 gap-4">
                         {[1,2,3,4].map(q => {
                             const key = `${selectedYear}-Q${q}`;
                             const data = stats.quarter[key];
                             const avg = data && data.scoredCount > 0 ? data.totalScore / data.scoredCount : 0;
                             const height = (avg / 10) * 100;

                             return (
                                 <div key={q} className="flex-1 flex flex-col items-center gap-1 group">
                                     <div className="w-full bg-zinc-800 rounded-t relative group-hover:bg-[#d8b17e]/50 transition-colors flex items-end justify-center" style={{ height: `${height}%` }}>
                                         <div className="text-[10px] font-bold text-white mb-1">{avg > 0 ? avg.toFixed(1) : '-'}</div>
                                     </div>
                                     <div className="text-[10px] text-zinc-500">{q}분기</div>
                                 </div>
                             )
                         })}
                    </div>
                 </div>
            </div>
        </div>
    );
};

export default AnalysisDashboard;